# Site settings
title: "Max Stein"
description: "CV on GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Max Stein"
resume_title:                   "Data Analyst | Data Science Enthusiast"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "max.stein.tm@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "058-489-30-57"
resume_contact_address:         "Israel, Tel-Aviv"

resume_header_contact_info:     "Israel, Tel-Aviv District •
                                (+972)58-489-30-57 •
                                max.stein.tm@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I have advanced mathematical skills, a strong
background in probability theory and statistics, good analytical skills,
proficiency with machine learning algorithms and relevant hands-on experience
with big data. Curious, ambitious and responsible learner, striving to develop
and eager for challenges.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
resume_section_accomplishments: true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/unidentified-user"
  resume_facebook_url:          "https://www.facebook.com/maxim.shovkun"
  resume_linkedin_url:          "https://www.linkedin.com/in/unidentified-user"
  # resume_hackerrank_url:        "https://www.hackerrank.com/Rosenstein"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-cayman
